name: CI Trivia DL

on:
  push:
    branches:
      - master #cada vez que se ejecuta un push sobre la rama master, se ejecuta este workflow

jobs:
  test:
    runs-on: ubuntu-latest #GitHub crea un entorno de ejecución con la última 
                            #versión de Ubuntu, para realizar la build de CI

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Instalar Pytest
        run: pip install pytest

      - name: Ejecutar pruebas
        run: python -m pytest